export const enLicense = `
## PLEASE READ THE FOLLOWING TERMS CAREFULLY:

**BY CLICKING “I ACCEPT,” OR BY DOWNLOADING, INSTALLING, OR OTHERWISE ACCESSING OR USING THE SERVICE**, YOU AGREE THAT YOU HAVE READ AND UNDERSTOOD, AND, AS A CONDITION TO YOUR USE OF THE SERVICE, YOU AGREE TO BE BOUND BY, THE FOLLOWING TERMS AND CONDITIONS, INCLUDING TOBOTO’S PRIVACY POLICY AND OTHER POLICIES REFERENCED BELOW (TOGETHER, THESE "**TERMS"). IF YOU ARE NOT ELIGIBLE, OR DO NOT AGREE TO THE TERMS, THEN YOU DO NOT HAVE OUR PERMISSION TO USE THE SERVICE. YOUR USE OF THE SERVICE, AND TOBOTO’S PROVISION OF THE SERVICE TO YOU, CONSTITUTES AN AGREEMENT BY Toboto AND BY YOU TO BE BOUND BY THESE TERMS.

**ARBITRATION NOTICE**. You agree that disputes arising under these Terms will be resolved by binding, individual arbitration, and BY ACCEPTING THESE TERMS, YOU AND TOBOTO ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN ANY CLASS ACTION OR REPRESENTATIVE PROCEEDING.

1. **Toboto Service Overview**. Toboto operates the Service as a marketplace for digital goods and services (the “Products”) where certain users (“Buyers”) can purchase the Products sold by other users (“Sellers” or “Renters”). All Products are provided solely by the applicable Seller or Renter and Toboto is not responsible for the Products sold through the Service.

2. **Eligibility**. You must be at least 13 years old to use the Service. By agreeing to these Terms, you represent and warrant to us that: (a) you are at least 13 years old; (b) you have not previously been suspended or removed from the Service; and (c) your registration and your use of the Service is in compliance with any and all applicable laws and regulations. If you are an entity, organization, or company, the individual accepting these Terms on your behalf represents and warrants that they have authority to bind you to these Terms and you agree to be bound by these Terms.

3. **Accounts and Registration**. To access most features of the Service, you must register for an account. When you register for an account, you may be required to provide us with some information about yourself, such as your name, email address, or other contact information, or to link certain outside accounts, such as a Google account, Twitter, Discord or a digital wallet (“Linked Accounts”). You agree that the information you provide to us is accurate, complete, and not misleading, and that you will keep it accurate and up to date at all times. You further agree that all Linked Accounts are your own and you have all necessary rights to link them to the Service.

4. **General Payment Terms**. Certain features of the Service, including the purchase or sale of certain Products, may require you to pay fees. Before you pay any fees, you will have an opportunity to review and accept the fees that you will be charged. All fees are denominated in the stated currency or other means of payment and are non-refundable unless otherwise specifically provided for in these Terms.

   **4.1 Price**. Toboto reserves the right to determine pricing for the Service and any fees it may charge on transactions conducted on the Service. Toboto will make reasonable efforts to keep pricing information published on the Service up to date. We encourage you to check our pricing page periodically for current pricing information. Toboto may change the fees for any feature of the Service, including additional fees or charges, if Toboto gives you advance notice of changes before they apply. Toboto, at its sole discretion, may make promotional offers with different features and different pricing to any of Toboto’s customers. These promotional offers, unless made to you, will not apply to your offer or these Terms.

   **4.2 Authorization.** You authorize Toboto to charge all sums for the orders that you make and any level of Service you select as described in these Terms or published by Toboto, including all applicable taxes, to the payment method specified by you. verify that the credit card is valid and has the necessary funds or credit available to cover your purchase.

5. **Third-Party Terms**

   **5.1 Third-Party Services and Linked Websites**. Toboto may provide tools through the Service that enable you to export information, including User Content, to third-party services, including through features that allow you to link your account on the Service with an account on the thirdparty service, such as Twitter or Discord, or through our implementation of third-party buttons (such as “like” or “share” buttons). By using one of these tools, you hereby authorize that Toboto to transfer that information to the applicable third-party service. Third-party services
   are not under Toboto’s control, and, to the fullest extent permitted by law, Toboto is not responsible for any third-party service’s use of your exported information. The Service may also contain links to third-party websites. Linked websites are not under Toboto’s control, and Toboto is not responsible for their content. Further, Toboto will not provide exports of third-party data. Please be sure to review the terms of use and privacy policy of any thirdparty services before you share any User Content or information with such thirdparty services. Once sharing occurs, Toboto will have no control over the information that has been shared.

   **5.2 Third-Party Software**. The Service may include or incorporate third-party software components that are generally available free of charge under licenses granting recipients broad rights to copy, modify, and distribute those components (“Third-Party Components”). Although the Service is provided to you subject to these Terms, nothing in these Terms prevents, restricts, or is intended to prevent or restrict you from obtaining Third-Party Components under the applicable third-party licenses or to limit your use of Third-Party Components under those thirdparty licenses.

6. **User Content**

   **6.1 User Content Generally**. Certain features of the Service may permit users to submit, upload, publish, broadcast, or otherwise transmit (“Post”) content to the Service, including Product images, descriptions, and any other works of authorship or other works (“User Content”). You retain any copyright and other proprietary rights that you may hold in the User Content that you Post to the Service, subject to the licenses granted in these Terms.

   **6.2 Limited License Grant to Toboto**. By Posting User Content to or via the Service, you grant Toboto a worldwide, non-exclusive, royalty-free, fully paid right and license (with the right to sublicense through multiple tiers) to host, store, transfer, publicly display, publicly perform (including by means of a digital audio transmission), communicate to the public, reproduce, modify for the purpose of formatting for display, create derivative works as authorized in these Terms, and distribute your User Content, in whole or in part, in any media formats and through any media channels, in each instance whether now known or hereafter developed. You agree to pay all monies owing to any person or entity resulting from Posting your User Content and from Toboto’s exercise of the license set forth in this Section.

   **6.3 You Must Have Rights to the Content You Post; User Content Representations and Warranties**. You must not Post User Content if you are not the owner of or are not fully authorized to grant rights in all of the elements of that User Content. Toboto disclaims any and all liability in connection with User Content. You are solely responsible for your User Content and the consequences of providing User Content via the Service. By providing User Content via the Service, you affirm, represent, and warrant to us that:

   (a) you are the creator and owner of the User Content, or have the necessary licenses, rights, consents, and permissions to authorize Toboto and users of the Service to use and distribute your User Content as necessary to exercise the licenses granted by you in this Section, in the manner contemplated by Toboto, the Service, and these Terms;
   (b) your User Content, and the Posting or other use of your User Content as contemplated by these Terms, does not and will not: (i) infringe, violate, misappropriate, or otherwise breach any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property, contract, or proprietary right; (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; or (iii) cause Toboto to violate any law or regulation or require us to obtain any further licenses from or pay any royalties, fees, compensation or other amounts or provide any attribution to any third parties; and
   (c) your User Content could not be deemed by a reasonable person to be objectionable, profane, indecent, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate.

   **6.4 User Content Disclaimer**. We are under no obligation to edit or control User Content that you or other users Post and will not be in any way responsible or l under no obligation to edit or control User Content that you or other users Post and will not be in any way responsible or liable for User Content. Toboto may, however, at any time and without prior notice, screen, remove, edit, or block any User Content that in our sole judgment violates these Terms, is alleged to violate the rights of third parties, or is otherwise objectionable. You understand that, when using the Service, you will be exposed to User Content from a variety of sources and acknowledge that User Content may be inaccurate, offensive, indecent, or objectionable. You agree to waive, and do waive, any legal or equitable right or remedy you have or may have against Toboto with respect to User Content. If notified by a user or content owner that User Content allegedly does not conform to these Terms, we may investigate the allegation and determine in our sole discretion whether to remove the User Content, which we reserve the right to do at any time and without notice. For clarity, Toboto does not permit infringing activities on the Service.

   **6.5 Monitoring Content**. Toboto does not control and does not have any obligation to monitor: (a) User Content; (b) any content made available by third parties; or (c) the use of the Service by its users. You acknowledge and agree that Toboto reserves the right to, and may from time to time, monitor any and all information transmitted or received through the Service for operational and other purposes. If at any time Toboto chooses to monitor the content, then Toboto still assumes no responsibility or liability for content or any loss or damage incurred as a result of the use of content. During monitoring, information may be examined, recorded, copied, and used in accordance with our Privacy Policy (defined below). Toboto may block, filter, mute, remove or disable access to any User Content uploaded to or transmitted through the Service without any liability to the user who Posted such User Content to the Service or to any other users of the Service. 

7. **Prohibited Conduct**. BY USING THE SERVICE, YOU AGREE NOT TO:

    7.1 use the Service or sell any Products for any illegal purpose or in violation of any local,state, national, or international law; 

    7.2 violate, encourage others to violate, or provide instructions on how to violate, any right of a third party, including by infringing or misappropriating any third-party intellectual property right;

    7.3 access, search, or otherwise use any portion of the Service through the use of any engine, software, tool, agent, device, or mechanism (including spiders, robots, crawlers, and data mining tools) other than the software or search agents provided by Toboto;

    7.4 interfere with security-related features of the Service, including by: (i) disabling or circumventing features that prevent or limit use, printing or copying of any content; or (ii) reverse engineering or otherwise attempting to discover the source code of any portion of the Service except to the extent that the activity is expressly permitted by applicable law;

    7.5 interfere with the operation of the Service or any user’s enjoyment of the Service, including by: (i) uploading or otherwise disseminating any virus, adware, spyware, worm, or other malicious code; (ii) making any unsolicited offer or advertisement to another user of the Service; (iii) collecting personal information about another user or third party without consent; or (iv) interfering with or disrupting any network, equipment, or server connected to or used to provide the Service (v) harassing any user with unsolicited, unwelcome, disrespectful, physically abusive or offensive behavior. Examples of harassment include, but are not limited to, user targeting attempts (social media bans, server bans, attacking other users’ social media), unwanted comments or remarks, jokes, slurs, online messages, unwanted physical intimidation or touch and literature including pictures and posters, depicting people in a negative light based on prohibited grounds, e.g. racial or religious harassment, age harassment, etc.

    7.6 perform any fraudulent activity including impersonating any person or entity, claiming a false affiliation or identity, accessing any other Service account without permission;

    7.7 sell or otherwise transfer the access granted under these Terms or any Materials (as defined in Section 6) or any right or ability to view, access, or use any Materials; or

    7.8 attempt to do any of the acts described in this Section 7 or assist 

8. **Modification of Terms**. We may, from time to time, change these Terms. Please check these Terms periodically for changes. Revisions will be effective immediately except that, for existing users, material revisions will be effective 30 days after posting or notice to you of the revisions unless otherwise stated. We may require that you accept modified Terms in order to continue to use the Service. If you do not agree to the modified Terms, then you should remove your User Content and discontinue your use of the Service. Except as expressly permitted in this Section 8, these Terms may be amended only by a written agreement signed by authorized representatives of the parties to these Terms. 

9. **Disclaimers; No Warranties by Toboto**

    9.1 THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE ARE PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS. TOBOTO DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, RELATING TO THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE, INCLUDING: (A) ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, OR NONINFRINGEMENT; AND (B) ANY WARRANTY ARISING OUT OF COURSE OF DEALING, USAGE, OR TRADE. TOBOTO DOES NOT WARRANT THAT THE SERVICE OR ANY PORTION OF THE SERVICE, OR ANY MATERIALS OR CONTENT OFFERED THROUGH THE SERVICE, WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS, AND TOBOTO DOES NOT WARRANT THAT ANY OF THOSE ISSUES WILL BE CORRECTED.

    9.2 ALL PRODUCTS ARE PROVIDED SOLELY BY THE APPLICABLE SELLER, ANY PURCHASE OR SALE OF PRODUCTS IS ONLY FACILITATED BY TOBOTO. YOU AGREE THAT TOBOTO WILL NOT HAVE ANY LIABILITY TO YOU, AND TOBOTO HEREBY DISCLAIMS ALL SUCH LIABILITY, REGARDING THE USE OR FUNCTION OF ANY PRODUCT. ANY DISPUTES REGARDING A PRODUCT ARE SOLELY BETWEEN THE APPLICABLE BUYER AND SELLER.

    9.3 NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE SERVICE OR TOBOTO ENTITIES OR ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE SERVICE WILL CREATE ANY WARRANTY REGARDING ANY OF THE TOBOTO ENTITIES OR THE SERVICE THAT IS NOT EXPRESSLY STATED IN THESE TERMS. WE ARE NOT RESPONSIBLE FOR ANY DAMAGE THAT MAY RESULT FROM THE SERVICE AND YOUR DEALING WITH ANY OTHER SERVICE USER. YOU UNDERSTAND AND AGREE THAT YOU USE ANY PORTION OF THE SERVICE AT YOUR OWN DISCRETION AND RISK, AND THAT WE ARE NOT RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM OR MOBILE DEVICE USED IN CONNECTION WITH THE SERVICE) OR ANY LOSS OF DATA, INCLUDING USER CONTENT.

    9.4 THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS IN THIS SECTION 9 APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. Toboto does not disclaim any warranty or other right that Toboto is prohibited from disclaiming under applicable law. 

10. **Limitation of Liability**

    10.1 TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL THE TOBOTO ENTITIES BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, OR ANY OTHER INTANGIBLE LOSS) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR YOUR INABILITY TO ACCESS OR USE, THE SERVICE OR ANY MATERIALS OR CONTENT ON THE SERVICE, WHETHER BASED ON  WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ANY TOBOTO ENTITY HAS BEEN INFORMED OF THE POSSIBILITY OF DAMAGE.

    10.2 EACH PROVISION OF THESE TERMS THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS INTENDED TO AND DOES ALLOCATE THE RISKS BETWEEN THE PARTIES UNDER THESE TERMS. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF THESE TERMS. THE LIMITATIONS IN THIS SECTION 10 WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. 
`
